config/routes.rb
HonorsDatabase::Application.routes.draw do
	resources :concentrations
	resources :courses
	resources :honors_applications
	resources :majors
	resources :minors
	resources :participations
	resources :semesters
	resources :students
	

  root :to => 'students#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/concentration.rb
class Concentration < ActiveRecord::Base
  attr_protected :id, :created_at, :updated_at
	
	#Cardinality
	has_and_belongs_to_many :students
	#ASSOCIATIONS
	#VALIDATIONS
	validates :concentration, presence: true
	
	def name
		return "#{self.concentration}"
	end
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_protected :id, :created_at, :updated_at
	
	#Cardinality
	has_and_belongs_to_many :students
	belongs_to :semester
	#ASSOCIATIONS
	#VALIDATIONS
	validates :CRN, presence: true, uniqueness: true, length: {is: 5}
	validates :course_ID, presence: true, numericality: {only_integer: true}
	validates :section_ID, presence: true, numericality: {only_integer: true}
	
	def name
		return "#{self.course_name}"
	end
end

app/models/honors_application.rb
class HonorsApplication < ActiveRecord::Base
	attr_protected :id, :created_at, :updated_at
	
	#Cardinality	
	belongs_to :student
	#ASSOCIATIONS
	#VALIDATIONS
	validates :combined_SAT, presence: true
	validates :math_SAT, presence: true
	validates :critical_reading_SAT, presence: true
	validates :writing_SAT, presence: true
	validates :essay_one, presence: true
	validates :essay_two, presence: true
	validates :high_school_GPA, presence: true
	validates :recommendation, presence: true
	
	def name
		unless (self.student.nil?)
			return "#{self.student.name} (Submitted: #{self.created_at})"
		end
		return "Submitted: #{self.created_at}"
	end
end

app/models/major.rb
class Major < ActiveRecord::Base
  attr_protected :id, :created_at, :updated_at
	
	#Cardinality
	has_and_belongs_to_many :students
	#ASSOCIATIONS
	#VALIDATIONS
	validates :major, presence: true
	
	def name
		return "#{self.major}"
	end
end

app/models/minor.rb
class Minor < ActiveRecord::Base
  attr_protected :id, :created_at, :updated_at
	
	#Cardinality
	has_and_belongs_to_many :students
	#ASSOCIATIONS
	#VALIDATIONS
	validates :minor, presence: true

	def name
		return "#{self.minor}"
	end
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  attr_protected :id, :created_at, :updated_at
	
	#Cardinality
	belongs_to :student
	belongs_to :semester
	#ASSOCIATIONS
	#VALIDATIONS
	validates :service, presence: true, numericality: true
	validates :activity, presence: true, numericality: true
	
	def name
		if (self.student.nil?)
			participation_name = "Unassociatied participation for "
		else
			participation_name = "#{self.student.name} for "
		end
		
		if (self.semester.nil?)
			participation_name += "unknown semester"
		else
			participation_name += "#{self.semester.name}"
		end
		
		return participation_name
	end
end

app/models/semester.rb
class Semester < ActiveRecord::Base
  attr_protected :id, :created_at, :updated_at
	
	#Cardinality
	has_many :courses
	has_many :participations
	#ASSOCIATIONS
	#VALIDATIONS
	validates :year, presence: true, numericality: {only_integer: true}
	validates :session, presence: true
	
	def name
		return "#{self.session} #{self.year}"
	end
end

app/models/student.rb
class Student < ActiveRecord::Base
	attr_protected :id, :created_at, :updated_at

	#Cardinality
	has_many :honors_applications
	has_many :participations
	has_and_belongs_to_many :majors
	has_and_belongs_to_many :minors
	has_and_belongs_to_many :concentrations
	has_and_belongs_to_many :courses
	#ASSOCIATIONS
	#VALIDATIONS
	validates :banner_ID, uniqueness: true, presence: true, length: {is: 9}
	validates :last_name, presence: true
	validates :first_name, presence: true
	validates :email, presence: true, email: true
	validates :street, presence: true
	validates :city, presence: true
	validates :state, presence: true, length: {is: 2}
	validates :enroll_session, presence: true
	validates :enroll_year, presence: true, numericality: {only_integer: true}
	validates :graduation_year, numericality: {only_integer: true}, allow_blank: true
	
	def name
		return "#{self.last_name}, #{self.first_name}"
	end
end

app/controllers/majors_controller.rb
class MajorsController < SuperController
	def index
		super(Major)
	end
	
	def show
		super(Major)
	end
	
	def new
		super(Major)
	end
	
	def create
		super(Major)
	end
	
	def edit
		super(Major)
	end
	
	def update
		super(Major)
	end
	
	def destroy
		super(Major)
	end
end

app/controllers/minors_controller.rb
class MinorsController < SuperController
	def index
		super(Minor)
	end
	
	def show
		super(Minor)
	end
	
	def new
		super(Minor)
	end
	
	def create
		super(Minor)
	end
	
	def edit
		super(Minor)
	end
	
	def update
		super(Minor)
	end
	
	def destroy
		super(Minor)
	end
end

app/controllers/super_controller.rb
class SuperController < ApplicationController
	def index(klass)
		@class = klass
		@objects = klass.all
	end
	
	def show(klass)
		@object = klass.find(params[:id])
	end
	
	def new(klass)
		@object = klass.new
	end
	
	def create(klass)
		@object = klass.new(params[klass.name.underscore.to_sym])
		add_associations(klass)
		if (@object.save)
			redirect_to @object
		else
			render 'new'
		end
	end
	
	def edit(klass)
		@object = klass.find(params[:id])
	end
	
	def update(klass)
		@object = klass.find(params[:id])
		if (@object.update_attributes(params[klass.name.underscore.to_sym]))
			add_associations(klass)
			redirect_to action: 'show', id: @object.id
		else
			render 'edit'
		end
	end
	
	def destroy(klass)
		@object = klass.find(params[:id])
		@object.destroy
		
		redirect_to action: 'index'
	end
	
	private
	
	def add_associations(klass)
		otm_associations = klass.reflect_on_all_associations(:belongs_to)
		mtm_associations = klass.reflect_on_all_associations(:has_and_belongs_to_many)
		otm_associations.each do |assoc|
			param_id = "#{assoc.plural_name.singularize}_id"
		  key = params[param_id.to_sym]
			unless (key.blank?)
				@object[param_id.to_sym] = key.to_i
			end
		end
		mtm_associations.each do |assoc|
			key = params[assoc.association_foreign_key.to_sym]
			unless (key.blank?)
				new_association = assoc.class_name.constantize.find(key)
				unless (new_association.blank?)
					add_association(
						@object.send(assoc.plural_name),
						key,
						new_association
					)
				end
			end
		end
	end

	def add_association(current_associations, new_assoc_key, new_assoc)
		unless (new_assoc_key.blank?)
			unless (current_associations.include?(new_assoc))
				current_associations << new_assoc
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def underscore
		word = self.dup
		word.gsub!(/::/, '/')
		word.gsub!(/([A-Z]+)([A-Z][a-z])/,'\1_\2')
		word.gsub!(/([a-z\d])([A-Z])/,'\1_\2')
		word.tr!("-", "_")
		word.downcase!
		return word
  end
end

app/helpers/concentration_helper.rb
module ConcentrationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/major_helper.rb
module MajorHelper
end

app/helpers/minor_helper.rb
module MinorHelper
end

app/helpers/participation_helper.rb
module ParticipationHelper
end

app/helpers/semester_helper.rb
module SemesterHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HonorsDatabase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_edit.html.erb
<h1>Edit <%= @object.class.model_name.human.titleize %></h1>
<%= render 'form' %>

app/views/shared/_form.html.erb
<%= form_for(@object) do |f| %>
  <% @object.attributes.each do |attribute| %>
    <% attr_name = attribute.first.to_s.titleize %>
    <% unless (attribute.first.eql?('id') or
               attribute.first.eql?('created_at') or
               attribute.first.eql?('updated_at') or
               attribute.first.end_with?('_id')) %>
      <div class="field">
        <% if (attribute.first.start_with?('is_')) %>
          <%= f.check_box attribute.first.to_sym%><%= attr_name %><br/>
        <% else %>
          <%= f.label attribute.first.to_sym, attr_name %>
          <%= f.text_field attribute.first.to_sym, {value: attribute.last}%>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <% mtm_associations =
    @object.class.reflect_on_all_associations(:has_and_belongs_to_many) %>
  <% otm_associations = @object.class.reflect_on_all_associations(:belongs_to) %>
  <% unless (otm_associations.empty?) %>
    <h1>Add One-to-Many Associations</h1>
    <% otm_associations.each do |assoc| %>
      <%= assoc.name %>
      <% param_id = "#{assoc.plural_name.singularize}_id" %>
      <%= collection_select(
        nil,
        param_id.to_sym,
        assoc.class_name.constantize.all.sort_by{|obj| obj.name},
        :id,
        :name,
        {:include_blank => true}
      ) %><br/>
    <% end %>
  <% end %>
  <% unless (mtm_associations.empty?) %>
    <h1>Add Many-to-Many Associations</h1>
    <% mtm_associations.each do |assoc| %>
      <%= assoc.name %>
      <%= collection_select(
        nil,
        assoc.association_foreign_key.to_sym,
        assoc.class_name.constantize.all.sort_by{|obj| obj.name},
        :id,
        :name,
        {include_blank: true}
      ) %><br/>
    <% end %>
  <% end %>
      
  <div class="errors">
    <% @object.errors.each do |attribute, error| %>
      <%= "#{attribute} #{error}"%><br/>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Create #{@object.class.model_name.human.titleize}",
      class: 'submit'%>
  </div>
<% end %>
<%= link_to 'Back', action: nil %>

app/views/shared/_index.html.erb
<%= render 'shared/menu' %>

<% class_name = @class.model_name.human.titleize %>
<h1>Listing <%= class_name.pluralize %></h1>
<table>
<% @objects.sort_by{|obj| obj.name}.each do |object| %>
  <tr>
    <td><%= link_to object.name, action: 'show', id: object.id %></td>
    <td><%= link_to 'Edit', action: 'edit', id: object.id %></td>
    <td><%= link_to 'Destroy', {action: 'destroy', id: object.id}, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to "New #{class_name}", action: 'new' %>

app/views/shared/_menu.html.erb
<%= link_to 'Concentrations', concentrations_path %><br/>
<%= link_to 'Courses', courses_path %><br/>
<%= link_to 'Honors Applications', honors_applications_path %><br/>
<%= link_to 'Majors', majors_path %><br/>
<%= link_to 'Minors', minors_path %><br/>
<%= link_to 'Participations', participations_path %><br/>
<%= link_to 'Semesters', semesters_path %><br/>
<%= link_to 'Students', students_path %><br/>

app/views/shared/_new.html.erb
<h1>New <%= @object.class.model_name.human.titleize %></h1>
<%= render 'form' %>

app/views/shared/_show.html.erb
<h1>Information for this <%= @object.class.model_name.human.titleize %></h1>
<% @object.attributes.each do |attribute| %>
  <% attr_name = attribute.first.to_s.split('_').map(&:titleize).join(' ') %>
  <% unless (attribute.first.to_s.eql?('id')) %>
    <% if (attribute.first.to_s[-3..-1].eql?('_id')) #It's a foreign key %>
      <%  class_name = attribute.first.to_s.gsub(/_id/i, "").pluralize.classify %>
      <div>
        <%=
          #attr_name separates the words with spaces.
          "#{attr_name.gsub(/ id/i, "")}:
          #{class_name.constantize.find(attribute.last.to_i).name}" 
        %>
      </div>
    <% else %>
      <div><%= "#{attr_name}:  #{attribute.last}" %></div>
    <% end %>
  <% end %>
<% end %>
<% mtm_associations =
    @object.class.reflect_on_all_associations(:has_and_belongs_to_many) %>
<% mtm_associations.each do |assoc_type| %>
  <h1><%= assoc_type.name.to_s.titleize %></h1>
  <% @object.send(assoc_type.plural_name).sort_by{|a| a.name}.each do |assoc_value| %>
    <%= assoc_value.name %><br/>
  <% end %>
<% end %>
<% otm_associations = @object.class.reflect_on_all_associations(:has_many) %>
<% otm_associations.each do |assoc_type| %>
  <h1><%= assoc_type.name.to_s.titleize %></h1>
  <% @object.send(assoc_type.plural_name).sort_by{|a| a.name}.each do |assoc_value| %>
    <%= assoc_value.name %><br/>
  <% end %>
<% end %>
<br/>
<%= link_to 'Edit', action: 'edit', id: @object.id %> |
<%= link_to 'Back', action: nil %>